# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ATkfMB6l8p5KXl0p7gcONb5Q52iH0Plf
"""

class Student:
  def __init__(self, name, id):
    self.name = name
    self.id = id

  def get_name(self):
    return self.name

  def get_id(self):
    return self.id